export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_FAIL = "CATEGORIES_FAIL";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORY_DELETED = "CATEGORY_DELETED";
export const CATEGORY_ADDING = "CATEGORY_ADDING";
export const CATEGORY_ADDED = "CATEGORY_ADDED";
export const CATEGORY_DELETING = "CATEGORY_DELETING";
export const CATEGORY_DELETING_FAILED = "CATEGORY_DELETING_FAILED";
